### ISSUE TITLE
Error: Program type already present: com.getcapacitor.AndroidProtocolHandler

### ISSUE THREAD

**Issue by kennrll18** [rahadur/capacitor-admob#12]
When i try to create a signed APK, i get the following error:
Error: Program type already present: com.getcapacitor.AndroidProtocolHandler

build failed | 2 s 115 ms
-- | --
Run build | 2 s 21 ms
Load build | 2 ms
Configure build | 319 ms
Calculate task graph | 38 ms
Run tasks | 1 s 659 ms
null |  
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'. |  
API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'. |  
null |  
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: |  
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: |  
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException: Error: Program type already present: com.getcapacitor.AndroidProtocolHandler |

**Comment by rahadur** [comment]
Please wait few moment. Currently i am working on this plugins within few hour i am going to upload a new version of this plugin. Thank you.

**Comment by rahadur** [comment]
@kennrll18 Please update your plugin with new version and let me know is that problem fixed or not.
```
npm i capacitor-admob
```

**Comment by rahadur** [comment]
due to no response i am closing this issue. you can re open if this problem arise
