### ISSUE TITLE
Cannot resolve symbol 'app'

### ISSUE THREAD

**Issue by ndhbr** [rahadur/capacitor-admob#13]
Hey,

first of all i want to say thank you for publishing this plugin.

Sadly i am unable to import into the MainActivity.
![Bildschirmfoto 2019-08-10 um 09 03 49](https://user-images.githubusercontent.com/13482230/62818914-563a1100-bb4e-11e9-977d-fbf9ec0d2aa2.png)

Related to https://github.com/rahadur/capacitor-admob/issues/6

**Comment by rahadur** [comment]
Closing this issue, it was solve here #6
