### ISSUE TITLE
Plugin doesn't show any add and error message

### ISSUE THREAD

**Issue by fermanquliyev** [rahadur/capacitor-admob#16]
I have written my app id and ad id as you showed in the documentation. But there is no any banner ad on my screen. I have debugged my app on chrome remote device tool, there is no any error on the console. Please help me

**Comment by fermanquliyev** [comment]
And although AdMob.ShowBanner method returns true value (succes) but no any ad displayed on page

**Comment by rahadur** [comment]
As long as you get true on `showBanner()` method that's mean plugin working properly on your app.

1. Open your app in Android Studio
2. Run application on your device or emulator.
3. Check your app logcat in Android Studio.

You will find AdMob logs with AdMob Tags. You will find some Error Code in logcat.

[Read this Community Question](https://support.google.com/admob/thread/3494603?hl=en) where you will find Error code meaning in details.

**Comment by rahadur** [comment]
due to inactivity i am going to close this issue. if required please reopen.
