### ISSUE TITLE
How to make it work with Ionic React?

### ISSUE THREAD

**Issue by adeoy** [rahadur/capacitor-admob#18]
Hi, I want to know if this plugin works for a Ionic React project. I have been searching for examples and plugins but  all of them are for Angular.
Thanks.

**Comment by lucnat** [comment]
Hi, I am using it in ionic react without problems. Just load initialize the banner in your App.js constructor: 

```
  constructor(props) {
    super(props);
    AdMob.initialize("your-app-id");
    // Show Banner Ad
    AdMob.showBanner(this.options).then(...)
  }
```

**Comment by adeoy** [comment]
Thanks for your response, I'm gonna try it, now I'm using Cordova with a React template, Onsen UI and Admob Plus Cordova Plugin. Ionic with React only caused me headaches.

**Comment by lucnat** [comment]
May I ask why? My experience was rather smooth so far with React and Ionic

**Comment by adeoy** [comment]
Because I couldn't put the ads, and I also I had problems to show downloaded files in the webview.
I agree with you, Ionic and React is faster and this is why I tried in first place, but I don't realized that the community is small so much problems aren't solved yet.
Since october 2019 I had these problem, so I switch to a more familiar platform and finished the job without problems.
