### ISSUE TITLE
The Google Mobile Ads SDK will not integrate with Firebase?

### ISSUE THREAD

**Issue by htorbov** [rahadur/capacitor-admob#23]
On iOS is working fine, but on Android I get:

> The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

I double-checked, I've followed every step from the README.

**Comment by rahadur** [comment]
@htorbov Thank you for your response.  i think i have to use AdMob Firebase SDK instance of default AdMob Sdk. I am going to release a new version by today, with updated Firebase SDK.

**Comment by rahadur** [comment]
@htorbov I just test this plugins `capacitor-admob@0.0.1` it's work properly on my side. can you please share more info such as`package.json` and Development Environment details so that i can better understand the problem. 

**Read Similar Issue:**  
[The Google Mobile Ads SDK will not integrate with Firebase.](https://groups.google.com/d/msg/google-admob-ads-sdk/kAAhkzmxbIk/t0vOvTfhAwAJ)

**Comment by htorbov** [comment]
@rahadur  thank you so much for the fast reply!

package.json:
```json
{
  "name": "foodprep",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "resources": "cordova-res ios && cordova-res android && node resources/resources.js"
  },
  "dependencies": {
    "@capacitor/android": "^1.4.0",
    "@capacitor/cli": "^1.4.0",
    "@capacitor/core": "^1.4.0",
    "@capacitor/ios": "^1.4.0",
    "@codetrix-studio/capacitor-google-auth": "^1.4.0",
    "@ionic/pwa-elements": "^1.4.1",
    "@rdlabo/capacitor-facebook-login": "^1.1.2",
    "axios": "^0.19.0",
    "capacitor-admob": "^0.1.0",
    "capacitor-apple-login": "git+https://github.com/htorbov/capacitor-apple-login.git",
    "core-js": "^3.4.3",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-google-adsense": "^1.8.0",
    "vue-meta": "^2.3.1",
    "vue-plugin-load-script": "^1.2.0",
    "vue-router": "^3.1.3",
    "vue-script2": "^2.1.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.1.0",
    "@vue/cli-plugin-eslint": "^4.1.0",
    "@vue/cli-plugin-pwa": "^4.1.0",
    "@vue/cli-plugin-router": "^4.1.0",
    "@vue/cli-plugin-vuex": "^4.1.0",
    "@vue/cli-service": "^4.1.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "sass": "^1.23.7",
    "sass-loader": "^8.0.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/standard"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

I'm using Vue with Capacitor (without Ionic or anything). I was wondering, I didn't find anywhere that Firebase was included in the code, I don't know why Google would want Firebase included in the project.. Strange..

**Comment by htorbov** [comment]
@rahadur I've just tested the demo - it works perfectly. I guess the problem is somewhere in my plugins, I'll try to track it now.

Anyway, one quick question - I was wondering, why there's no Native Ads implementation? Is it actually possible to ad them in Capacitor, or it's just not ready yet?

Thanks!
