### ISSUE TITLE
Banner and Interstitial ads used the same Event Listener.

### ISSUE THREAD

**Issue by vuqarsuleymanov** [rahadur/capacitor-admob#29]
Banner AD Event Listener

addListener(eventName: 'onAdLoaded', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdFailedToLoad', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdOpened', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdClosed', listenerFunc: (info: any) => void): PluginListenerHandle;

Interstitial AD Event Listener

addListener(eventName: 'onAdLoaded', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdFailedToLoad', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdOpened', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdClosed', listenerFunc: (info: any) => void): PluginListenerHandle;
addListener(eventName: 'onAdLeftApplication', listenerFunc: (info: any) => void): PluginListenerHandle;

Please split event listeners for banner and interstitial

**Comment by rahadur** [comment]
@vuqarsuleymanov I already split all **Event  Listener** in README file!

[Banner Events](https://github.com/rahadur/capacitor-admob#event-listener)

[Interstitial Events](https://github.com/rahadur/capacitor-admob#event-listener-1)

[Reward Video Events](https://github.com/rahadur/capacitor-admob#event-listener-2)

Thank you.
