### ISSUE TITLE
Cause: startup failed

### ISSUE THREAD

**Issue by prantikv** [rahadur/capacitor-admob#7]
Hey there,

Getting the following error while building. It seems to be a path typo.

```
Cause: startup failed:
script 'E:\Development\Capacitor\capAdmob\android\capacitor.settings.gradle': 6: unexpected char: '\' @ line 6, column 91.
   odules/capacitor-admob/android\capacitor
                                 ^

1 error
```

The error is persistent as the `capacitor.settings.gradle` file is generated every time.

Thanks

**Comment by rahadur** [comment]
this problem is now fixed.
