### ISSUE TITLE
Interstitial showing only in first time

### ISSUE THREAD

**Issue by pedroclericuzi** [rahadur/capacitor-admob#70]
I followed the steps of the tutorial and the Ad Interstitial appear only in the first time and after this does not work more and show this error `Error: The interstitial wasn't loaded yet.`
**The code:**
`  options: AdOptions = {
    adId: "ca-app-pub-3940256099942544/1033173712",
    autoShow: false
  };`

`constructor() { 
    // Prepare interstitial banner
    AdMob.prepareInterstitial(this.options).then(
      value => {
        console.log(value); // true
      },
      error => {
        console.error("pvbc - " + error); // show error
      }
    );
    AdMob.addListener("onAdLoaded", (info: boolean) => {
      // You can call showInterstitial() here or anytime you want.
      console.log("Interstitial Ad Loaded");
    });
  }`

`// Show interstitial ad when it’s ready
    AdMob.showInterstitial().then(
      value => {
        console.log(value); // true
      },
      error => {
        console.error(error); // show error
      }
  );`

**Comment by xErik** [comment]
Automatically reloading it on specific events works for me. This is probably desired to ensure that a new ad is shown --- and to avoid presenting already displayed ads.

```

  optionsInterstitial: AdOptions = {
    adId: 'ca-app-pub-3940256099942544/8691691433', // GOOGLE DUMMY VIDEO
    adSize: AdSize.SMART_BANNER,
    position: AdPosition.BOTTOM_CENTER,
    hasTabBar: false, 
    tabBarHeight: 56, 
  };

constructor() {
    AdMob.initialize(this.adMobAppId).then(() => {
      this.prepareInterstitial();
    });
}

AdMob.addListener('onAdClosed', (info: boolean) => {
      console.log('AdClosed');
      this.prepareInterstitial();
});

AdMob.addListener('onAdLeftApplication', (info: boolean) => {
      console.log('AdLeftApplication');
      this.prepareInterstitial();
});

prepareInterstitial() {
    AdMob.prepareInterstitial(this.optionsInterstitial).then(
      (value) => {
        console.log(value);
      },
      (error) => {
        console.error(error);
      }
    );
  }
```

**Comment by pedroclericuzi** [comment]
Thanks man, it works!! :D

**Comment by xErik** [comment]
Welcome, you may now close this issue ;-)
