### ISSUE TITLE
Test flag.

### ISSUE THREAD

**Issue by prantikv** [rahadur/capacitor-admob#8]
Hey there,

I have been considering using Capacitor in a public app. I have been testing the plugin and feel that there should be a test flag.

I have run into issues with apps where while testing the app was using a live Admob Ad ID and Admob flagged the app as it detected suspicious activity.

I have been using the Test Ids as given here [https://developers.google.com/admob/android/test-ads](https://developers.google.com/admob/android/test-ads)

This should be mentioned in the docs as, there is a risk of being flaged by Admob.

I have not been able to find **Test App IDs** though.

Would love to a parameter which can be truned on which does this.

**Comment by sta55en** [comment]
You might find this useful: https://developers.google.com/admob/ios/test-ads
